import AiIcon from './AiIcon.jsx'
const FEATURES = [
  { icon: <AiIcon />, title: 'AI Assistant', desc: 'Conversational intelligence grounded in live quotes, AI scores and market news. Multilingual, with source attribution, confidence levels and per-user chat history.' },
  { icon: '▤', title: 'Agentic Stock Scoring', desc: 'A daily multi-agent pipeline scores every script in the universe 0-100 using a proprietary blend of fundamentals, technicals, valuation, momentum, earnings, news sentiment, institutional activity and risk.' },
  { icon: '↺', title: 'On-demand Rescore', desc: 'Refresh any script score with a live quote at any time, with day-over-day change, the pillars that drove the move, and an AI-written rationale.' },
  { icon: '◈', title: 'Market News Intelligence', desc: 'Continuous collection from leading Indian financial sources, AI-summarized, tagged with impacted stocks, sectors and sentiment, linked to the original article.' },
  { icon: '◐', title: 'Portfolio Intelligence', desc: 'Health score with a transparent deduction breakdown, diversification metrics, concentration risk (HHI), sector exposure and factual AI insights.' },
  { icon: '☆', title: 'Personal Watchlist', desc: 'Follow any script with live price, day change and its latest AI score in one view.' },
  { icon: '⚙', title: 'Agents Dashboard', desc: 'Live operations view for admins: which bots are running, real-time progress, per-agent timings, scheduled jobs and run history.' },
  { icon: '⛨', title: 'Maker-Checker Governance', desc: 'Every score passes an automated Quality Agent gate plus an optional strict mode that holds scores as pending until a human admin approves them. Every decision is attributed and audit-logged.' },
  { icon: '◎', title: 'Independent AI Checker', desc: 'A second LLM (a different provider than the one that wrote the rationale, when available) independently reviews every score rationale for compliance and factual consistency before publishing. Flagged items are blocked or held for human review.' },
  { icon: '❏', title: 'Broker-Research RAG', desc: 'Upload the firm research notes (PDF/text); the assistant retrieves and cites the most relevant passages to ground its answers, reporting them factually as reference material rather than advice.' },
  { icon: '⬡', title: 'Multi-LLM Engine', desc: 'Anthropic Claude, OpenAI GPT and Google Gemini behind one router with automatic failover - no single-vendor dependency, with per-call usage tracked.' },
  { icon: '⚒', title: 'Fully DB-Configurable', desc: 'NIFTY500 instruments master with one-click import from NSE, editable scoring weights, scheduler times, chatbot persona and limits - all from the Admin tab.' },
  { icon: '⇄', title: 'Open APIs', desc: 'REST APIs for Ask AI, Stock Score, News Summary, Portfolio Analysis and Watchlist Insights - JWT-secured and ready for mobile app integration.' },
]

export default function About() {
  return (
    <div>
      <div className="panel about-hero">
        <h3>AI Investment Intelligence Platform</h3>
        <p className="hint">
          Explainable, agentic AI for Indian markets - combining large language models,
          live market data and transparent governance to deliver conversational insight,
          daily stock scoring and portfolio analytics inside your broking experience.
        </p>
        <p className="hint">Version 0.3 - Built for SEBI-regulated broking</p>
      </div>

      <div className="feature-grid">
        {FEATURES.map(f => (
          <div key={f.title} className="feature-card">
            <div className="feature-icon">{f.icon}</div>
            <h4>{f.title}</h4>
            <p>{f.desc}</p>
          </div>
        ))}
      </div>

      <div className="panel">
        <h4>Important information</h4>
        <p className="hint">
          All AI outputs in this application - scores, insights, summaries and chat
          responses - are generated by artificial intelligence for informational purposes
          only. They are not investment advice, research reports, or recommendations to
          buy or sell securities, and must be reviewed and approved before business or
          regulatory use. Investments in securities markets are subject to market risks.
          Please consult a SEBI-registered investment adviser before investing.
        </p>
      </div>
    </div>
  )
}
