import { useEffect, useState } from 'react'
import { api } from '../api.js'
import { SCORE_DEFINITION } from './Scores.jsx'
import Pager from './Pager.jsx'

export default function Watchlist() {
  const [rows, setRows] = useState([])
  const [all, setAll] = useState([])
  const [pick, setPick] = useState('')
  const [err, setErr] = useState('')
  const [busy, setBusy] = useState(false)
  const [page, setPage] = useState(0)

  const load = () => api.watchlist().then(d => setRows(d.watchlist)).catch(e => setErr(e.message))
  useEffect(() => {
    load()
    api.instruments().then(d => setAll(d.instruments)).catch(() => {})
  }, [])

  async function add() {
    const sym = pick.trim().toUpperCase()
    if (!sym) return
    setBusy(true); setErr('')
    try { await api.watchAdd(sym); setPick(''); await load() }
    catch (e) { setErr(e.message) }
    setBusy(false)
  }

  async function remove(sym) {
    try { await api.watchRemove(sym); await load() } catch (e) { setErr(e.message) }
  }

  return (
    <div>
      <div className="toolbar">
        <input list="inst-list" value={pick} placeholder="Add script (e.g. RELIANCE)"
               onChange={e => setPick(e.target.value)}
               onKeyDown={e => e.key === 'Enter' && add()} />
        <datalist id="inst-list">
          {all.map(i => <option key={i.symbol} value={i.symbol}>{i.name}</option>)}
        </datalist>
        <button onClick={add} disabled={busy || !pick.trim()}>Add</button>
        <button className="ghost" onClick={load}>Refresh</button>
      </div>
      {err && <p className="note">{err}</p>}
      {rows.length === 0 && <p className="hint">Your watchlist is empty — add scripts above.</p>}
      {rows.length > 0 && (
        <table className="data-table">
          <thead><tr>
            <th title="NSE trading symbol">Script</th>
            <th title="Latest traded price from the live market data feed">Last price</th>
            <th title="Percentage change vs previous close">Day change</th>
            <th title={SCORE_DEFINITION}>AI score / 100 <span className="info-i">i</span></th>
            <th title="Date the AI score was generated by the daily pipeline">Score date</th>
            <th />
          </tr></thead>
          <tbody>
            {rows.slice(page * 20, page * 20 + 20).map(r => (
              <tr key={r.symbol}>
                <td><strong>{r.symbol}</strong></td>
                <td>{r.last_price != null ? `₹${r.last_price.toLocaleString('en-IN')}` : '—'}</td>
                <td className={r.change_pct >= 0 ? 'up' : 'down'}>
                  {r.change_pct != null ? `${r.change_pct > 0 ? '+' : ''}${r.change_pct}%` : '—'}</td>
                <td>{r.ai_score != null ? r.ai_score : '—'}</td>
                <td>{r.score_date || '—'}</td>
                <td><button className="ghost" onClick={() => remove(r.symbol)}>Remove</button></td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
      <Pager page={page} setPage={setPage} total={rows.length} label="scripts" />
    </div>
  )
}
