import { useEffect, useState } from 'react'
import { api } from '../api.js'
import { fmtDate } from '../fmt.js'
import { SCORE_DEFINITION } from './Scores.jsx'
import Pager from './Pager.jsx'

const scoreColor = v =>
  v == null ? 'var(--muted)' : v >= 65 ? 'var(--green)' : v >= 45 ? 'var(--amber)' : 'var(--red)'
const fmtCr = v =>
  v == null ? '—' : '₹' + Math.round(v / 1e7).toLocaleString('en-IN') + ' Cr'
const band = v => v == null ? '' : v >= 65 ? 'Strong' : v >= 45 ? 'Neutral' : 'Weak'

export default function Watchlist({ scoreLabel = 'NIYTRI Score' }) {
  const [rows, setRows] = useState([])
  const [all, setAll] = useState([])
  const [pick, setPick] = useState('')
  const [err, setErr] = useState('')
  const [busy, setBusy] = useState(false)
  const [page, setPage] = useState(0)

  const load = () => api.watchlist().then(d => setRows(d.watchlist)).catch(e => setErr(e.message))
  useEffect(() => {
    load()
    api.instruments().then(d => setAll(d.instruments)).catch(() => {})
  }, [])

  async function add() {
    const sym = pick.trim().toUpperCase()
    if (!sym) return
    setBusy(true); setErr('')
    try { await api.watchAdd(sym); setPick(''); await load() }
    catch (e) { setErr(e.message) }
    setBusy(false)
  }

  async function remove(sym) {
    try { await api.watchRemove(sym); await load() } catch (e) { setErr(e.message) }
  }

  const scored = rows.filter(r => r.ai_score != null)
  const avg = scored.length
    ? Math.round(scored.reduce((a, r) => a + r.ai_score, 0) / scored.length * 10) / 10 : null
  const gainers = rows.filter(r => (r.change_pct ?? 0) > 0).length

  return (
    <div>
      <div className="toolbar">
        <input list="inst-list" value={pick} placeholder="Add script (e.g. RELIANCE)"
               onChange={e => setPick(e.target.value)}
               onKeyDown={e => e.key === 'Enter' && add()} />
        <datalist id="inst-list">
          {all.map(i => <option key={i.symbol} value={i.symbol}>{i.name}</option>)}
        </datalist>
        <button onClick={add} disabled={busy || !pick.trim()}>Add</button>
        <button className="ghost" onClick={load}>Refresh</button>
      </div>

      {err && <p className="note">{err}</p>}
      {rows.length === 0 && <p className="hint">Your watchlist is empty — add scripts above.</p>}

      {rows.length > 0 && (
        <div className="kpi-row" style={{ marginBottom: 14 }}>
          <div className="kpi"><span className="kpi-label">Scripts</span>
            <span className="kpi-value">{rows.length}</span></div>
          <div className="kpi" title="Average AI score across watchlist scripts that have a score">
            <span className="kpi-label">Avg {scoreLabel}</span>
            <span className="kpi-value" style={{ color: scoreColor(avg) }}>{avg ?? '—'}</span></div>
          <div className="kpi" title="Scripts trading up today"><span className="kpi-label">Up today</span>
            <span className="kpi-value up">{gainers}/{rows.length}</span></div>
        </div>
      )}

      {rows.length > 0 && (
        <table className="data-table">
          <thead><tr>
            <th title="NSE trading symbol and company">Script</th>
            <th title="Last traded price and % change vs previous close">Price (LTP)</th>
            <th title={SCORE_DEFINITION}>{scoreLabel} / 100 <span className="info-i">i</span></th>
            <th title="Trailing P/E captured at scoring time">P/E</th>
            <th title="Market capitalisation (₹ crore)">Mkt cap</th>
            <th title="Date the AI score was generated by the daily pipeline">Score date</th>
            <th />
          </tr></thead>
          <tbody>
            {rows.slice(page * 20, page * 20 + 20).map(r => {
              const up = (r.change_pct ?? 0) >= 0
              const d = r.score_delta
              const dpct = (d != null && r.prev_score) ? (d / r.prev_score * 100) : null
              return (
                <tr key={r.symbol}>
                  <td>
                    <div><strong>{r.symbol}</strong></div>
                    {r.name && <div className="hint" style={{ fontSize: '.82em' }}>{r.name}</div>}
                    {r.sector && <span className="tag" style={{ marginTop: 4 }}>{r.sector}</span>}
                  </td>
                  <td>
                    <div style={{ fontWeight: 600 }}>
                      {r.last_price != null ? '₹' + r.last_price.toLocaleString('en-IN') : '—'}</div>
                    {r.change_pct != null && (
                      <div className={up ? 'up' : 'down'} style={{ fontSize: '.85em' }}>
                        {up ? '▲' : '▼'} {up ? '+' : ''}{r.change_pct}%</div>)}
                  </td>
                  <td>
                    {r.ai_score != null
                      ? <span className="score" style={{ background: scoreColor(r.ai_score) }}
                              title={band(r.ai_score)}>{r.ai_score}</span>
                      : <span className="hint">—</span>}
                    {d != null && (
                      <div className={d > 0 ? 'up' : d < 0 ? 'down' : 'hint'}
                           style={{ fontSize: '.82em', marginTop: 4 }}
                           title="Change vs previous scoring day">
                        {d > 0 ? '▲' : d < 0 ? '▼' : '–'} {Math.abs(d)}
                        {dpct != null ? ` (${d > 0 ? '+' : d < 0 ? '−' : ''}${Math.abs(dpct).toFixed(1)}%)` : ''}
                      </div>)}
                  </td>
                  <td>{r.pe != null ? Number(r.pe).toFixed(1) : '—'}</td>
                  <td>{fmtCr(r.market_cap)}</td>
                  <td>{fmtDate(r.score_date)}</td>
                  <td><button className="ghost sm" onClick={() => remove(r.symbol)}>Remove</button></td>
                </tr>
              )
            })}
          </tbody>
        </table>
      )}
      <Pager page={page} setPage={setPage} total={rows.length} label="scripts" />
    </div>
  )
}
