-- ============================================================================
-- AI Investment Intelligence Platform — PostgreSQL initialization script
-- Target: AWS RDS PostgreSQL 13+
--
-- Run as the RDS master user, e.g.:
--   psql "host=YOUR-RDS-ENDPOINT.rds.amazonaws.com port=5432 user=postgres dbname=postgres sslmode=require" -f init_postgres.sql
--
-- DB name : broking_ai
-- App role: broking_app  (least-privilege; CHANGE THE PASSWORD below)
-- Schema  : public (4 tables: users, stock_scores, news_items, chat_messages)
--
-- Note: the backend's SQLAlchemy create_all() would also create these tables
-- automatically; this script exists so your DBA can provision them explicitly
-- with a controlled role and review the DDL.
-- ============================================================================

-- 1) Application role (login user the backend connects as)
--    >>> CHANGE THIS PASSWORD, then put the same value in backend/.env DATABASE_URL
CREATE ROLE broking_app WITH LOGIN PASSWORD 'CHANGE_ME_strong_password';

-- 2) Database
CREATE DATABASE broking_ai OWNER broking_app;

-- ─── Reconnect to the new database before the rest ──────────────────────────
\connect broking_ai

SET ROLE broking_app;

-- 3) Tables ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS users (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR NOT NULL UNIQUE,
    full_name       VARCHAR DEFAULT '',
    hashed_password VARCHAR NOT NULL,           -- bcrypt hash, never plaintext
    is_admin        BOOLEAN DEFAULT FALSE,
    is_active       BOOLEAN DEFAULT TRUE,
    created_at      TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_users_email ON users (email);

CREATE TABLE IF NOT EXISTS instruments (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol              VARCHAR NOT NULL UNIQUE,    -- NSE symbol
    name                VARCHAR DEFAULT '',
    sector              VARCHAR DEFAULT '',
    is_active           BOOLEAN DEFAULT TRUE,       -- visible in app
    in_scoring_universe BOOLEAN DEFAULT TRUE,       -- scored daily
    created_at          TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_instruments_symbol ON instruments (symbol);
-- NIFTY50 seed rows are inserted automatically by the backend on first startup
-- (only when the table is empty); manage from Admin → Instruments afterwards.

CREATE TABLE IF NOT EXISTS app_settings (
    key        VARCHAR PRIMARY KEY,                 -- e.g. scoring_weights
    value      JSON,
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS watchlist_items (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER NOT NULL,
    symbol     VARCHAR NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT uq_watch_user_symbol UNIQUE (user_id, symbol),
    CONSTRAINT fk_watch_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX IF NOT EXISTS ix_watchlist_items_user_id ON watchlist_items (user_id);

CREATE TABLE IF NOT EXISTS stock_scores (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol          VARCHAR NOT NULL,
    score_date      VARCHAR NOT NULL,           -- YYYY-MM-DD
    composite_score DOUBLE PRECISION,
    pillar_scores   JSON,                       -- {fundamental, technical, ...}
    explanation     TEXT,
    quality_status  VARCHAR DEFAULT 'pending',  -- pending | approved | rejected
    reviewed_by     VARCHAR DEFAULT '',         -- admin email (maker-checker)
    reviewed_at     TIMESTAMPTZ,
    ai_review       JSON,                        -- independent AI checker verdict
    created_at      TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_stock_scores_symbol ON stock_scores (symbol);
CREATE INDEX IF NOT EXISTS ix_stock_scores_score_date ON stock_scores (score_date);

CREATE TABLE IF NOT EXISTS pipeline_runs (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id        VARCHAR UNIQUE,
    started       TIMESTAMPTZ,
    finished      TIMESTAMPTZ,
    status        VARCHAR,                       -- completed | partial | failed
    symbols_count INTEGER DEFAULT 0,
    symbols       JSON,
    agents        JSON,
    created_at    TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_pipeline_runs_run_id ON pipeline_runs (run_id);

-- Broker-research RAG store
CREATE TABLE IF NOT EXISTS research_documents (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR,
    source           VARCHAR DEFAULT '',
    filename         VARCHAR DEFAULT '',
    uploaded_by      VARCHAR DEFAULT '',
    chunk_count      INTEGER DEFAULT 0,
    embedding_method VARCHAR DEFAULT '',
    created_at       TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS research_chunks (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id INTEGER NOT NULL,
    ordinal     INTEGER DEFAULT 0,
    text        TEXT,
    embedding   JSON,                            -- list[float]
    created_at  TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT fk_chunk_doc FOREIGN KEY (document_id) REFERENCES research_documents (id)
);
CREATE INDEX IF NOT EXISTS ix_research_chunks_document_id ON research_chunks (document_id);

CREATE TABLE IF NOT EXISTS news_items (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            TEXT,
    link             VARCHAR UNIQUE,
    source           VARCHAR,
    published        VARCHAR,
    summary_short    TEXT,
    summary_detailed TEXT,
    impacted_stocks  JSON,
    impacted_sectors JSON,
    sentiment        VARCHAR,
    created_at       TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER,                          -- FK to users (nullable)
    session_id VARCHAR,
    role       VARCHAR,                          -- user | assistant
    content    TEXT,
    meta       JSON,                             -- provider, confidence, ...
    created_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT fk_chat_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX IF NOT EXISTS ix_chat_messages_user_id ON chat_messages (user_id);
CREATE INDEX IF NOT EXISTS ix_chat_messages_session_id ON chat_messages (session_id);

RESET ROLE;

-- 4) Admin user
--    Do NOT insert the admin here (passwords must be bcrypt-hashed).
--    After the schema exists, run from backend/ on your machine:
--        python scripts\create_admin.py
--    It prompts for email + password interactively and stores only the hash.

-- ============================================================================
-- backend/.env then needs:
-- DATABASE_URL=postgresql+psycopg2://broking_app:YOUR_PASSWORD@YOUR-RDS-ENDPOINT.rds.amazonaws.com:5432/broking_ai?sslmode=require
-- ============================================================================
