-- ============================================================================
-- UPGRADE v3 — run on an existing database to add the objects for:
--   • Independent AI checker        (stock_scores.ai_review)
--   • Broker-research RAG store      (research_documents, research_chunks)
-- Idempotent — safe to run more than once.
--
--   psql "host=YOUR-RDS-ENDPOINT.rds.amazonaws.com port=5432 user=postgres dbname=broking_ai sslmode=require" -f upgrade_v3.sql
--
-- (Fresh installs: use init_postgres.sql instead — it already includes these.)
-- Strict maker-checker mode needs NO schema change — it is a runtime setting
-- toggled in Admin → Settings (stored in the existing app_settings table).
-- ============================================================================

-- Independent AI checker verdict per published score
ALTER TABLE stock_scores ADD COLUMN IF NOT EXISTS ai_review JSON;

-- Broker-research RAG store
CREATE TABLE IF NOT EXISTS research_documents (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR,
    source           VARCHAR DEFAULT '',
    filename         VARCHAR DEFAULT '',
    uploaded_by      VARCHAR DEFAULT '',
    chunk_count      INTEGER DEFAULT 0,
    embedding_method VARCHAR DEFAULT '',
    created_at       TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS research_chunks (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id INTEGER NOT NULL,
    ordinal     INTEGER DEFAULT 0,
    text        TEXT,
    embedding   JSON,
    created_at  TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT fk_chunk_doc FOREIGN KEY (document_id) REFERENCES research_documents (id)
);
CREATE INDEX IF NOT EXISTS ix_research_chunks_document_id ON research_chunks (document_id);

-- Grant to the app role (skip if broking_app owns the database)
GRANT SELECT, INSERT, UPDATE, DELETE ON research_documents, research_chunks TO broking_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO broking_app;
