-- ============================================================================
-- UPGRADE v7 — Self-service registration: invite-only + referrals, Google auth,
-- waitlist, and per-email invitations. Idempotent. Run in pgAdmin against broking_ai.
-- (The backend also creates these on startup; this is for the DB-first workflow.)
-- ============================================================================

-- New columns on users -------------------------------------------------------
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_code    VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS invited_by_code  VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_provider    VARCHAR DEFAULT 'email';
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified   BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS verify_token     VARCHAR;
CREATE UNIQUE INDEX IF NOT EXISTS ix_users_referral_code ON users (referral_code);

-- Invite codes (member codes + admin seed codes) -----------------------------
CREATE TABLE IF NOT EXISTS invite_codes (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR UNIQUE,
    owner_user_id INTEGER,                 -- NULL = admin seed code
    max_uses      INTEGER DEFAULT 5,
    used_count    INTEGER DEFAULT 0,
    is_active     BOOLEAN DEFAULT TRUE,
    created_by    VARCHAR DEFAULT '',
    created_at    TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_invite_codes_code  ON invite_codes (code);
CREATE INDEX IF NOT EXISTS ix_invite_codes_owner ON invite_codes (owner_user_id);

-- Waitlist -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS waitlist (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR UNIQUE,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_waitlist_email ON waitlist (email);

-- Per-email invitations (up to invites_per_user per member) -------------------
CREATE TABLE IF NOT EXISTS invitations (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inviter_user_id INTEGER,
    email           VARCHAR,
    code            VARCHAR,               -- the inviter's referral code shared
    status          VARCHAR DEFAULT 'sent',
    delivered       BOOLEAN DEFAULT FALSE, -- true if the email was actually sent
    created_at      TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT uq_invite_once UNIQUE (inviter_user_id, email)
);
CREATE INDEX IF NOT EXISTS ix_invitations_inviter ON invitations (inviter_user_id);
CREATE INDEX IF NOT EXISTS ix_invitations_email   ON invitations (email);

-- Permissions for the application role ----------------------------------------
-- Only granted if a role named "broking_app" exists (skip cleanly otherwise —
-- if your app connects as the table owner, these grants aren't needed at all).
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'broking_app') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON invite_codes, waitlist, invitations TO broking_app;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO broking_app;
  END IF;
END $$;
