-- ============================================================================
-- UPGRADE script — run this if you already created the database with the
-- original init_postgres.sql. Adds the v2 tables (instruments master,
-- app settings, watchlists). Idempotent — safe to run twice.
--
--   psql "host=YOUR-RDS-ENDPOINT.rds.amazonaws.com port=5432 user=postgres dbname=broking_ai sslmode=require" -f upgrade_v2.sql
--
-- (Fresh installs: use init_postgres.sql instead — it already includes these.)
-- ============================================================================

CREATE TABLE IF NOT EXISTS instruments (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol              VARCHAR NOT NULL UNIQUE,
    name                VARCHAR DEFAULT '',
    sector              VARCHAR DEFAULT '',
    is_active           BOOLEAN DEFAULT TRUE,
    in_scoring_universe BOOLEAN DEFAULT TRUE,
    created_at          TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_instruments_symbol ON instruments (symbol);

CREATE TABLE IF NOT EXISTS app_settings (
    key        VARCHAR PRIMARY KEY,
    value      JSON,
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS watchlist_items (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER NOT NULL,
    symbol     VARCHAR NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT uq_watch_user_symbol UNIQUE (user_id, symbol),
    CONSTRAINT fk_watch_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX IF NOT EXISTS ix_watchlist_items_user_id ON watchlist_items (user_id);

-- Columns added since v1 (no-ops if already present)
ALTER TABLE stock_scores  ADD COLUMN IF NOT EXISTS reviewed_by VARCHAR DEFAULT '';
ALTER TABLE stock_scores  ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS user_id INTEGER;

-- Grant to the app role (skip if broking_app owns the database)
GRANT SELECT, INSERT, UPDATE, DELETE ON instruments, app_settings, watchlist_items TO broking_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO broking_app;

-- NIFTY50 instruments are seeded automatically by the backend on next startup
-- (only when the instruments table is empty). Manage via Admin → Instruments.
