-- ============================================================================
-- UPGRADE v6 — Open Partner API keys + Score-crossing Alerts (in-app feed).
-- Idempotent. Run in pgAdmin against broking_ai. (The backend also creates these
-- tables automatically on startup via init_db(); this is for the DB-first workflow.)
-- ============================================================================

-- Partner Open API keys (hashed; scoped; rate-limited) --------------------------
CREATE TABLE IF NOT EXISTS partner_keys (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR,
    key_prefix         VARCHAR,               -- shown for identification (e.g. niy_live_ab12cd)
    key_hash           VARCHAR UNIQUE,        -- sha256 of the full key (plaintext never stored)
    scopes             JSON,                  -- ["scores","news","ask","portfolio"]
    rate_limit_per_min INTEGER DEFAULT 60,
    is_active          BOOLEAN DEFAULT TRUE,
    created_by         VARCHAR DEFAULT '',
    last_used_at       TIMESTAMPTZ,
    call_count         INTEGER DEFAULT 0,
    created_at         TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_partner_keys_key_prefix ON partner_keys (key_prefix);
CREATE INDEX IF NOT EXISTS ix_partner_keys_key_hash   ON partner_keys (key_hash);

-- Score-crossing alerts (per user; one row per user/symbol/date/kind) -----------
CREATE TABLE IF NOT EXISTS alerts (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER,
    symbol     VARCHAR,
    score_date VARCHAR,
    kind       VARCHAR,                       -- band_up | band_down | jump | drop
    from_score DOUBLE PRECISION,
    to_score   DOUBLE PRECISION,
    delta      DOUBLE PRECISION,
    from_band  VARCHAR DEFAULT '',            -- strong | neutral | weak
    to_band    VARCHAR DEFAULT '',
    source     VARCHAR DEFAULT '',            -- watchlist | portfolio
    message    TEXT DEFAULT '',
    is_read    BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT uq_alert_once UNIQUE (user_id, symbol, score_date, kind)
);
CREATE INDEX IF NOT EXISTS ix_alerts_user_id     ON alerts (user_id);
CREATE INDEX IF NOT EXISTS ix_alerts_symbol      ON alerts (symbol);
CREATE INDEX IF NOT EXISTS ix_alerts_score_date  ON alerts (score_date);
CREATE INDEX IF NOT EXISTS ix_alerts_user_read   ON alerts (user_id, is_read);


-- Profile photo column on users (idempotent) ----------------------------------
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar TEXT;

-- Per-user alert preferences (one row per user) --------------------------------
CREATE TABLE IF NOT EXISTS alert_prefs (
    user_id       INTEGER PRIMARY KEY,
    enabled       BOOLEAN DEFAULT TRUE,
    bands         BOOLEAN DEFAULT TRUE,          -- band-crossing alerts
    jumps         BOOLEAN DEFAULT TRUE,          -- sharp same-band moves
    min_jump      DOUBLE PRECISION,              -- personal threshold; null -> use global
    muted_symbols JSON,                          -- list[str] of suppressed symbols
    updated_at    TIMESTAMPTZ DEFAULT now()
);

-- Permissions for the application role ------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON partner_keys, alerts, alert_prefs TO broking_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO broking_app;
