-- ============================================================================
-- UPGRADE v8 — Email verification token + user-activity fields (signup/last IP,
-- last login). Idempotent. Run in pgAdmin against broking_ai. The backend also
-- adds these on startup; this is for the DB-first workflow.
-- ============================================================================

ALTER TABLE users ADD COLUMN IF NOT EXISTS verify_token   VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS signup_ip      VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_ip        VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at  TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS session_id     VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tos_accepted    BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tos_version     VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tos_seq         INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tos_accepted_at TIMESTAMPTZ;

-- New tables (also auto-created by the backend on startup) -------------------
CREATE TABLE IF NOT EXISTS email_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    to_addr VARCHAR, subject VARCHAR, kind VARCHAR, provider VARCHAR,
    delivered BOOLEAN DEFAULT FALSE, error VARCHAR DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX IF NOT EXISTS ix_email_logs_created ON email_logs (created_at);

CREATE TABLE IF NOT EXISTS tos_acceptances (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER, email VARCHAR, version VARCHAR, seq INTEGER, ip VARCHAR,
    accepted_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX IF NOT EXISTS ix_tos_acc_user ON tos_acceptances (user_id);

CREATE TABLE IF NOT EXISTS terms_versions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seq INTEGER, version VARCHAR, html TEXT, created_by VARCHAR DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT now());

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'broking_app') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON email_logs, tos_acceptances, terms_versions TO broking_app;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO broking_app;
  END IF;
END $$;
