-- ============================================================================
-- UPGRADE v4 — RBAC: roles table + users.role_id, with seeded roles.
-- Idempotent. Run in pgAdmin against the broking_ai database.
-- (The backend also auto-applies these on startup; this script is for the
--  DB-first / DBA-controlled workflow.)
-- ============================================================================

-- 1) Page-permission roles
CREATE TABLE IF NOT EXISTS roles (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR NOT NULL UNIQUE,
    pages      JSON,                       -- list of allowed page names
    is_admin   BOOLEAN DEFAULT FALSE,      -- grants Agents/Audit/Admin + admin APIs
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_roles_name ON roles (name);

-- 2) Link users to a role
ALTER TABLE users ADD COLUMN IF NOT EXISTS role_id INTEGER;

-- 3) Seed the two built-in roles (idempotent)
INSERT INTO roles (name, pages, is_admin) VALUES
  ('Administrator',
   '["Dashboard","AI Assistant","Stock Scores","Market News","Watchlist","Portfolio","About","Agents","Audit","Admin"]',
   TRUE)
ON CONFLICT (name) DO NOTHING;

INSERT INTO roles (name, pages, is_admin) VALUES
  ('User',
   '["Dashboard","AI Assistant","Stock Scores","Market News","Watchlist","Portfolio","About"]',
   FALSE)
ON CONFLICT (name) DO NOTHING;

-- 4) (Optional) attach existing admin accounts to the Administrator role
-- UPDATE users SET role_id = (SELECT id FROM roles WHERE name = 'Administrator')
--   WHERE is_admin = TRUE AND role_id IS NULL;

-- 5) Grant to the app role (skip if broking_app owns the database)
GRANT SELECT, INSERT, UPDATE, DELETE ON roles TO broking_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO broking_app;
