-- ============================================================================
-- UPGRADE v5 — per-user saved portfolios (uploaded or hand-entered holdings).
-- Idempotent. Run in pgAdmin against broking_ai. (The backend also creates this
-- table automatically on startup; this is for the DB-first workflow.)
-- ============================================================================
CREATE TABLE IF NOT EXISTS portfolios (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    INTEGER NOT NULL UNIQUE,
    holdings   JSON,                         -- [{symbol, quantity, avg_price, sector}]
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_portfolios_user_id ON portfolios (user_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON portfolios TO broking_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO broking_app;
